# Default fini configuration file.

database_path: '~/.config/fini/fini.sqlite3'

action:
  default: 'code'
  rules:
    meet:
      - '^Met\b'
    email:
      - '\bEmailed\b'
    admin:
      - null
context:
  default: 'frontend'
  rules:
    backend:
      - '\brails\b'
      - '\bdjango\b'
    mobile:
      - '\bandroid\b'
      - '\bios\b'
