# Default configuration for Fini
# Users can override these values in ~/.config/fini/config.yml

database_path: '~/.config/fini/fini.sqlite3'

# Inference rules for action and context
infer_rules:
  action:
    meet:
      - '^Met\b'
    plan:
      - '\bsprint\b'
    code:
      - '^PR'
      - '^Updated PR'
      - '^Worked'
      - '^Refactored'
    review:
      - '\breviewed PR\b'
  context:
    events:
      - '\bevent\b'
      - '\bevents\b'
    ops:
      - '\[ops-request\]'
    collections:
      - '\bcollection\b'
    rails:
      - '\bsprint\b'
    developers:
      - '\bdevelopers\b'
    bugs:
      - '\bissue\b'
    rwgps:
      - '\ball( |-)staff\b'
    mobile:
      - '\bandroid\b'
      - '\bios\b'
      - '\bApple JWT\b'
